name: "Continuous Deployment"

on: 
  push:
    tags:
      - "*"

jobs:

  #############################################################################
  # Create and online deployment of the documentation #########################
  docs: #######################################################################
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"

    - name: Install Dependencies (conda and pip)
      shell: bash
      run: |
        conda install --yes -c conda-forge pythonocc-core 
        python -m pip install --upgrade pip
        python -m pip install .[doc]

    - name: Build Documentation
      run: |
        make html
      working-directory: docs/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        allow_empty_commit: true
  
  #############################################################################      
  ## Create a public "Release" on the Github page #############################
  release_github: #############################################################
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
